name: upper-build

on:
    push:
        paths:
            - ".github/workflows/upper-build.yml"
            - "upper/**"
    workflow_dispatch: #manual 

jobs:
    build:
        name: go build
        runs-on: ubuntu-latest
        steps:
         - run: pwd && ls -al 
           name: printing current working directory along with list of contents before checking out code
         - uses: actions/checkout@v4
         - run: pwd && ls -al 
           name: printing current working directory after checking out source code
         - run: go version
           name: checking default go version from the github runner
         - uses: actions/setup-go@v5
           with:
            # go-version: '1.22'
            go-version-file: ./upper/go.mod
            cache-dependency-path: ./upper/go.sum
           name: setup and installation for go version from go.sum dependecy package file 
         - run: go version 
         - run: | 
            ls 
            go build 
            ls 
            go test
           name: go build and test 
           working-directory: upper

            

