name: go packaging

on:
    push:
        paths:
            - ".github/workflows/go-packaging.yml"
            - "upper/**"
    workflow_dispatch: #manual

jobs:
    packaging:
        permissions:
            contents: write
        strategy:
            matrix:
                os: [ ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os}}
        defaults:
            run:
                working-directory: upper
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: 1.22
                cache-dependency-path: ./upper/go.sum
            - run: ./build.xplat.sh
            - uses: softprops/action-gh-release@v2
              with:
                files: ./upper/bin/upper*
                body: "Binaries for the go command line tool "
                tag_name: ${{github.ref_name}}
            - run: ls 
            - run: go build 
            - run: ls 
            - run: go test -v 
            # - uses: actions/upload-artifact@v4
            #   with: 
            #     path: ./upper/upper*
            #     name: "artifact-${{matrix.os}}"