name: go packaging

on:
    push:
        paths:
            - ".github/workflows/go-packaging.yml"
            - "upper/**"
    workflow_dispatch: #manual

jobs:
    packaging:
        runs-on: ubuntu-latest 
        defaults:
            run:
                working-directory: upper
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: 1.22
                cache-dependency-path: ./upper/go.sum
            - run: ls 
            - run: go build 
            - run: ls 
            - run: go test -v 
            - uses: actions/upload-artifact@v4
              with: 
                path: ./upper/upper 
                name: artifact