name: upper-build

on:
    push:
        paths:
            - ".github/workflows/upper-build.yml"
            - "upper/**"
    workflow_dispatch: #manual 

jobs:
    build:
        name: go build
        runs-on: ubuntu-latest
        steps:
         - run: go version

